# Site settings
name: Arun sudharsan
title: Arun sudharsan | Software Engineer
description: Software engineer passionate in problem solving.
url: https://arun-sudharsan.github.io/
baseurl: ''
email: arunmsudharsan@gmail.com
cover: https://arun-sudharsan.github.io/img/og.png
logo: https://arun-sudharsan.github.io/img/emojis/technologist.png
resume: https://arun-sudharsan.github.io/resume.pdf
social:
  - title: email
    url: mailto:arunmsudharsan@gmail.com
  - title: twitter
    url: https://twitter.com/ASudharsan
  - title: instagram
    url: https://instagram.com/arunm619
  - title: github
    url: https://github.com/arunm619
  - title: linkedin
    url: https://www.linkedin.com/in/arunm619/

# Build settings
markdown: kramdown

exclude:
  - 'Gemfile'
  - 'Gemfile.lock'
  - '*.gemspec'
  - 'README.md'
  - 'node_modules'
  - 'build'
  - 'gulpfile.js'
  - 'package.json'

keep_files:
  - 'CNAME'
  - '.git'
  - '.gitignore'

plugins_dir:
  - jekyll-minifier
  - jekyll-sitemap
