# Site settings
name: Hariharan .J
title:  Hariharan | mechanical Engineer
description: Mechanical engineer passionate in problem solving.
url: https://hariharan0709.github.io/
baseurl: ''
email: hariharanj0709@gmail.com
cover: https://hariharan0709.github.io/img/og.png
logo: https://hariharan0709.github.io/img/emojis/technologist.png
resume: https://hariharan0709.github.io/resume.pdf
social:
  - title: email
    url: mailto:arunmsudharsan@gmail.com
  - title: twitter
    url: https://twitter.com/hariharan768
  - title: instagram
    url: https://instagram.com//hari_haran__j
  - title: github
    url: https://github.com/hariharan0709
  - title: linkedin
    url: https://www.linkedin.com/in/hari-haran-38411b157/

# Build settings
markdown: kramdown

exclude:
  - 'Gemfile'
  - 'Gemfile.lock'
  - '*.gemspec'
  - 'README.md'
  - 'node_modules'
  - 'build'
  - 'gulpfile.js'
  - 'package.json'

keep_files:
  - 'CNAME'
  - '.git'
  - '.gitignore'

plugins_dir:
  - jekyll-minifier
  - jekyll-sitemap
